language: python
python:
  - '3.5'

# Route builds to Travis CI's container-based infrastructure.
sudo: false

cache: pip
install:
  - pip install -U pip
  - pip install -r requirements.txt
script: inv quality

deploy:
  provider: pypi
  user: rlucioni
  password:
    secure: SN+gNGIMSeZlo8DR46xRfu1c2XcMBTlR9cQypBEkEnyhO4HnAroU/HBDhwWE2oxOznSq0CCC2rO6U7raO0FWTG3Wca3XyNk4+tIN/7VGvwBiLOdPx6bSODK16ZARYWTJRbr5E4rGLxhA8A+02QgIUjY7gEJMDurfXXpe+jqY86eapc3xZpRwaUTMU8FpMHE3mxeA6A84uHiCR/a3TC0tEifYTbpcX1i9f0s0S9qkLkkrTjVqIokUr1fs6R5jtGSd3Poz9ZoN0oHFzgcE+cIFuJrGrWI4aavaEj09g5EOLGXEjqh6ikHCtLszHFE53XGLYGitliD9rRIWwxsuV5eXR2h4aQ5AHN9HHIbEVE3KVmQz2JQTNtgfXB0DB82R8GndTuGKCw/u0KnQm50C9LecYX1n0gvbsZXQo3Km0WFKSu6UvVCc0rQKsvPdjkdjSdemap7K5i9hmPgRenbMbeiOtOppHCgoXf4nZoGorViVVviSur58IjyJMuC/RV3wNMDjftQA8zGloqtt63npQfEdVyrs6Mb6P7XEcsF+Q7Lh2ATsIp6oJEnfjcnSENmIyl8ouzxbhJC+hMxZLMfz80sfqH7PKp0AwLDBUulIBzs05aAANxoq141s1kk3hEgGiH42Y3YzMxDZEpAFbS3kF2FZkyWRGLrEMvogppewk/5Q19o=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: rlucioni/clockit
